# ============================================
# CONEXIÓN A SUPABASE - SESSION POOLER (puerto 5432)
# ============================================

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres

# Username
spring.datasource.username=postgres.pvjrlzawyipwrdwujxex

# Password
spring.datasource.password=Camilasebas@2026

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA - POSTGRESQL
# ============================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# SEGURIDAD
# ============================================
api.key=123456

# ============================================
# PUERTO
# ============================================
server.port=8080

# ============================================
# LOGS
# ============================================
logging.level.com.seguros=DEBUG
logging.level.org.hibernate.SQL=DEBUG